#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

OriginalTestDir=../SVD
ConfigDir=$TEST_DIR/$OriginalTestDir

cp -f $TEST_DIR/$OriginalTestDir/baseline* $TEST_DIR

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun cntk.cntk 'reader=[readerType=NewHTKMLFReader] reader=[prefetch=true]' || exit $?
