#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

OriginalTestDir=../QuickE2E
ConfigDir=$TEST_DIR/$OriginalTestDir

cp -f $TEST_DIR/$OriginalTestDir/baseline* $TEST_DIR

# cntkrun <CNTK config file name> <additional CNTK args>
DeleteModelsAfterTest=0
cntkrun cntk.cntk 'reader=[readerType=NewHTKMLFReader] reader=[prefetch=true]' || exit $?
echo === Deleting last epoch data
rm $TEST_RUN_DIR/models/*.dnn
echo ==== Re-running from checkpoint
DeleteExistingModels=0
DeleteModelsAfterTest=1
# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun cntk.cntk 'makeMode=true reader=[readerType=NewHTKMLFReader] reader=[prefetch=true]' || exit $?
